# Generated by Django 5.0.1 on 2024-08-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='address',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='contactno',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='username',
        ),
    ]
