# Generated by Django 5.0.1 on 2024-08-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
