# Generated by Django 5.0.1 on 2024-08-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_member_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='skills',
        ),
        migrations.AddField(
            model_name='member',
            name='selected_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
