# Generated by Django 5.0.1 on 2024-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='selected_skills',
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
