# Generated by Django 5.0.1 on 2024-08-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_videoconference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoConference',
        ),
    ]
