# Generated by Django 5.0.1 on 2024-09-01 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_videoconference'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconference',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
