# Generated by Django 5.0.1 on 2024-09-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_videoconference_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconference',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='videoconference',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbnails/default-thumbnail.png', null=True, upload_to='thumbnails/'),
        ),
    ]
